[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
preDeployCommand = "alembic upgrade head"
restartPolicyType = "on_failure"
healthcheckPath = "/health"
healthcheckTimeout = 100
rootDirectory = "/"
