import React, { useState } from 'react';
import { FileText, Download, Settings, CheckCircle, AlertCircle } from 'lucide-react';
import { reportingService } from '../services/reporting';
import { AccessibleButton } from './ui/AccessibleButton';
import { secureLogger } from '../utils/secureLogger';

interface DigitalDossierGeneratorProps {
  caseId?: string;
  className?: string;
}

interface DossierSection {
  id: string;
  title: string;
  description: string;
  included: boolean;
  content?: string;
}

const DigitalDossierGenerator: React.FC<DigitalDossierGeneratorProps> = ({
  caseId,
  className = ''
}) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedDossier, setGeneratedDossier] = useState<string | null>(null);
  const [sections, setSections] = useState<DossierSection[]>([
    {
      id: 'executive-summary',
      title: 'Executive Summary',
      description: 'High-level overview of the investigation findings',
      included: true
    },
    {
      id: 'case-timeline',
      title: 'Case Timeline',
      description: 'Chronological sequence of key events and discoveries',
      included: true
    },
    {
      id: 'evidence-summary',
      title: 'Evidence Summary',
      description: 'Overview of all collected evidence and chain of custody',
      included: true
    },
    {
      id: 'analysis-findings',
      title: 'Analysis & Findings',
      description: 'Detailed analysis of patterns, anomalies, and conclusions',
      included: true
    },
    {
      id: 'entity-relationships',
      title: 'Entity Relationships',
      description: 'Network analysis of involved parties and connections',
      included: false
    },
    {
      id: 'recommendations',
      title: 'Recommendations',
      description: 'Suggested next steps and preventive measures',
      included: true
    },
    {
      id: 'appendices',
      title: 'Appendices',
      description: 'Supporting documents, data tables, and raw evidence',
      included: false
    }
  ]);

  const toggleSection = (sectionId: string) => {
    setSections(sections.map(section =>
      section.id === sectionId
        ? { ...section, included: !section.included }
        : section
    ));
  };

  const generateDossier = async () => {
    if (!caseId) return;
    setIsGenerating(true);

    try {
      const summary = await reportingService.getCaseSummary(caseId);
      
      let content = `# Digital Investigation Dossier\n`;
      content += `**Case ID:** ${caseId}\n`;
      content += `**Generated:** ${new Date().toLocaleString()}\n`;
      content += `**Status:** ${summary.stats.status.toUpperCase()}\n\n`;

      const includedSections = sections.filter(s => s.included);
      content += `## Table of Contents\n${includedSections.map((s, i) => `${i + 1}. ${s.title}`).join('\n')}\n\n`;

      for (const section of includedSections) {
         content += `## ${section.title}\n\n`;
         if (section.id === 'executive-summary') {
             content += `**Data Quality:** ${summary.stats.dataQuality}%\n`;
             content += `**Flagged Amount:** $${summary.stats.flaggedAmount.toLocaleString()}\n`;
             content += `**Resolution Time:** ${summary.stats.daysToResolution} days\n`;
             content += `**Confirmed Fraud:** ${summary.stats.confirmedFraud}\n\n`;
         } else if (section.id === 'analysis-findings') {
             content += summary.findings.map(f => `- [${f.severity.toUpperCase()}] ${f.description}`).join('\n');
             content += '\n\n';
         } else {
             content += `${section.description}\n\n[Detailed content pending full integration]\n\n`;
         }
      }
      
      content += `---\n*Generated by Fraud Detection Platform*`;
      setGeneratedDossier(content);
      } catch (error) {
        secureLogger.error('DOSSIER_GENERATOR', 'Failed to generate dossier', {
          error: error instanceof Error ? error.message : String(error),
          caseId
        });
    } finally {
        setIsGenerating(false);
    }
  };

  const downloadDossier = () => {
    if (!generatedDossier) return;

    const blob = new Blob([generatedDossier], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `dossier-${caseId || 'case'}-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const includedCount = sections.filter(s => s.included).length;

  return (
    <div className={`digital-dossier-generator bg-white dark:bg-slate-900 rounded-lg border border-slate-200 dark:border-slate-800 p-6 ${className}`}>
      <div className="flex items-center gap-3 mb-6">
        <FileText className="text-blue-500" size={24} />
        <div>
          <h3 className="text-xl font-semibold text-slate-900 dark:text-white">
            Digital Dossier Generator
          </h3>
          <p className="text-slate-600 dark:text-slate-400">
            Case: {caseId || 'No case selected'}
          </p>
        </div>
      </div>

      {!generatedDossier ? (
        <>
          {/* Section Configuration */}
          <div className="mb-6">
            <h4 className="text-lg font-medium text-slate-900 dark:text-white mb-3">
              Configure Dossier Sections
            </h4>
            <p className="text-slate-600 dark:text-slate-400 mb-4">
              Select which sections to include in the generated dossier ({includedCount} of {sections.length} selected)
            </p>

            <div className="space-y-3">
              {sections.map(section => (
                <div
                  key={section.id}
                  className="flex items-start gap-3 p-3 border border-slate-200 dark:border-slate-700 rounded-lg"
                >
                  <input
                    type="checkbox"
                    id={`section-${section.id}`}
                    checked={section.included}
                    onChange={() => toggleSection(section.id)}
                    className="mt-1"
                    aria-label={`Include ${section.title} section`}
                  />
                  <div className="flex-1">
                    <label
                      htmlFor={`section-${section.id}`}
                      className="font-medium text-slate-900 dark:text-white cursor-pointer"
                    >
                      {section.title}
                    </label>
                    <p className="text-sm text-slate-600 dark:text-slate-400 mt-1">
                      {section.description}
                    </p>
                  </div>
                  {section.included && (
                    <CheckCircle className="text-green-500 mt-1" size={16} />
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Generation Controls */}
          <div className="flex items-center justify-between pt-4 border-t border-slate-200 dark:border-slate-700">
            <div className="text-sm text-slate-600 dark:text-slate-400">
              {includedCount === 0 && (
                <span className="flex items-center gap-1 text-red-600 dark:text-red-400">
                  <AlertCircle size={16} />
                  Select at least one section
                </span>
              )}
              {includedCount > 0 && (
                <span>Ready to generate dossier with {includedCount} section{includedCount !== 1 ? 's' : ''}</span>
              )}
            </div>

            <AccessibleButton
              onClick={generateDossier}
              disabled={includedCount === 0 || isGenerating || !caseId}
              variant="primary"
              aria-label="Generate digital dossier"
            >
              {isGenerating ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Generating...
                </>
              ) : (
                <>
                  <FileText size={16} className="mr-2" />
                  Generate Dossier
                </>
              )}
            </AccessibleButton>
          </div>
        </>
      ) : (
        <>
          {/* Generated Dossier Display */}
          <div className="mb-6">
            <div className="flex items-center gap-2 mb-3">
              <CheckCircle className="text-green-500" size={20} />
              <h4 className="text-lg font-medium text-slate-900 dark:text-white">
                Dossier Generated Successfully
              </h4>
            </div>

            <div className="bg-slate-50 dark:bg-slate-800 rounded-lg p-4 max-h-96 overflow-y-auto">
              <pre className="text-sm text-slate-900 dark:text-slate-100 whitespace-pre-wrap font-mono">
                {generatedDossier}
              </pre>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-3 pt-4 border-t border-slate-200 dark:border-slate-700">
            <AccessibleButton
              onClick={() => setGeneratedDossier(null)}
              variant="secondary"
              aria-label="Configure new dossier"
            >
              <Settings size={16} className="mr-2" />
              Configure New
            </AccessibleButton>

            <AccessibleButton
              onClick={downloadDossier}
              variant="primary"
              aria-label="Download dossier as markdown file"
            >
              <Download size={16} className="mr-2" />
              Download Dossier
            </AccessibleButton>
          </div>
        </>
      )}
    </div>
  );
};

export default DigitalDossierGenerator;
