import os
import sys
from datetime import datetime

import pytest

# Add backend to path for imports to work if running from root
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../")))

from app.services.fraud.engine import RuleEngine


@pytest.mark.asyncio
async def test_fraud_plugins_integration():
    """
    Test that the RuleEngine correctly loads and executes fraud detection plugins.
    """
    print("Initializing RuleEngine...")
    engine = RuleEngine()

    # Wait for async initialization if possible, but RuleEngine wraps it in sync
    # Verify plugins are loaded
    assert len(engine.rules) > 0, "No plugins loaded into RuleEngine"
    print(f"Loaded rules: {list(engine.rules.keys())}")

    # Mock transactions
    transactions = [
        # Mirror Transaction sequence
        {
            "id": "tx1",
            "amount": 5000,
            "date": datetime.now().isoformat(),
            "type": "CREDIT",
            "customer_id": "C1",
            "merchant_name": "M1",
        },
        {
            "id": "tx2",
            "amount": 5000,
            "date": datetime.now().isoformat(),
            "type": "DEBIT",
            "customer_id": "C1",
            "merchant_name": "M1",
        },
        # Shell Company indicators
        {
            "id": "tx3",
            "amount": 5500,
            "date": datetime.now().isoformat(),
            "type": "DEBIT",
            "customer_id": "C2",
            "merchant_name": "SuspiciousShell",
        },
        {
            "id": "tx4",
            "amount": 5450,
            "date": datetime.now().isoformat(),
            "type": "CREDIT",
            "customer_id": "C3",
            "merchant_name": "SuspiciousShell",
        },
        # Structuring
        {
            "id": "tx5",
            "amount": 9000,
            "date": datetime.now().isoformat(),
            "type": "DEBIT",
            "customer_id": "C_Struct",
            "merchant_name": "M2",
        },
        {
            "id": "tx6",
            "amount": 9500,
            "date": datetime.now().isoformat(),
            "type": "DEBIT",
            "customer_id": "C_Struct",
            "merchant_name": "M3",
        },
        {
            "id": "tx7",
            "amount": 9200,
            "date": datetime.now().isoformat(),
            "type": "DEBIT",
            "customer_id": "C_Struct",
            "merchant_name": "M4",
        },
    ]

    print(f"Executing rules on {len(transactions)} transactions...")
    alerts = engine.execute_rules(transactions)

    print(f"Generated {len(alerts)} alerts.")

    assert len(alerts) > 0, "No alerts generated by plugins"

    # Check for specific alert types
    rule_names = {a.rule_name for a in alerts}
    assert "mirror_transaction" in rule_names
    assert "structuring" in rule_names
    # Shell company check might depend on specific indicator matching, but likely triggered
    assert "shell_company" in rule_names
