apiVersion: v1
kind: Service
metadata:
  name: fraud-backend-service
  namespace: fraud-detection
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: fraud-backend
  type: ClusterIP
